version: '2'
services:
  db:
    image: postgres:10-alpine
    volumes:
      - './database:/var/lib/postgresql/data'
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8099:8080
  web:
    build: .
    command: bundle exec rails s -p 3099 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3099:3099"
    depends_on:
      - db
    restart: always